# Generated by Django 2.2 on 2020-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(default='new', max_length=20, verbose_name='Не проверено'),
        ),
    ]
