# Generated by Django 2.2 on 2020-07-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_note_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
    ]
