# Generated by Django 2.2 on 2020-07-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200727_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='note',
            name='todo_at',
            field=models.DateTimeField(null=True, verbose_name='Время завершения задачи'),
        ),
    ]
